# Number of minutes before the quest can be redone
redoMinuts: 5
# Chosen lang (file name) Available by default: fr_FR, en_US, zh_CN
lang: en_US
# > 1.13 Chosen Minecraft vanilla translations (JSON file name). Some can be found on SkytAsul's Discord server
minecraftTranslationsFile: null
# Enable or disable update checking on the loading
checkUpdates: true
# Enable or disable prefix before plugin message
enablePrefix: true
# Number of minutes between two periodic saves
saveCycle: 15
# ID of the quest who will be started on first connection of players (to disable: -1)
firstQuest: -1
# Max amount of quests who can be started at the same time by a player (you can bypass this limit for some quests)
maxLaunchedQuests: 0

# Enable or disable the scoreboards - more options in scoreboard.yml
scoreboards: true
# Enable or disable message when a quest is updated (next stage)
playerQuestUpdateMessage: true
# Enable or disable default messages when a stage starts
playerStageStartMessage: true
# Allows player to cancel quests they have started with the GUI
allowPlayerCancelQuest: false
# Enable of disable playing sounds on various actions
sounds: true
# Sound played at the end of a quest
finishSound: ENTITY_PLAYER_LEVELUP
# Enable or disable end fireworks
fireworks: true
# Show a progress bar (bossbar) when a player has to kill some mobs for a quest
mobsProgressBar: false
# Amount of seconds before the progress bar will disappear (set it to 0 to make it persistent)
progressBarTimeoutSeconds: 15
# Item who represents a quest in the Choose Quest GUI
item: BOOK
# Page item material
pageItem: ARROW

# - Dependencies -
# Enable GPS integration
gps: false
# Enable or disable SkillAPI experience overriding in xp reward/requirement
skillAPIoverride: true
# Enable or disable AccountsHook managing player accounts
accountsHook: false
# Max amount of lines for the splitted placeholder %beautyquests_started_ordered_X%
splittedAdvancementPlaceholderMax: 3
# Disable the hologram above NPC's head
disableTextHologram: false
# Value added to the hologram height (decimal value)
hologramsHeight: 0.0
# Material name of the hologram showed above head of Quests starter. If ProtocolLib is enabled, holograms will be visible only by players who can start the quest
holoLaunchItemName: BOOK
# Material name of the hologram showed above head of Stage NPC. If ProtocolLib is enabled, holograms will be visible only by players who has to talk with this NPC
holoTalkItemName: COAL
# dynmap integration options
dynmap:
  markerSetName: "Quests"
  markerIcon: "bookshelf"

# - Stage descriptions -
# Prefix before object's name in lists (example: §6first, §6second and §6third)
itemNameColor: "§6"
# Prefix before object's amount in lists (example: first§ex2, second§ex7 and third§ex4)
itemAmountColor: "§e"
stageDescriptionItemsSplit:
  # Prefix before each line
  prefix: "§e- §6"
  # Show "x1" if there is only one object
  showXOne: true
  # From which sources the text has to be split
  sources: [SCOREBOARD, MENU]


# - Particles configuration -
# enabled: will the particle be shown?
# particleEffect: name of the particle
# particleColor: for colored particles, RGB value of the color
# particleShape: shape of the particle effect (available: point, near, bar, exclamation, spot)

# Particles shown on a NPC when the player can start the quest
start:
  enabled: true
  particleEffect: redstone
  particleColor:
    RED: 255
    BLUE: 0
    GREEN: 255
  particleShape: point
# Particles shown on the NPC to which the player has to talk
talk:
  enabled: true
  particleEffect: villager_happy
  particleColor:
    RED: 255
    BLUE: 0
    GREEN: 255
  particleShape: bar
# Particles shown when the player finish a stage of a quest
next:
  enabled: true
  particleEffect: smoke_normal
  particleColor:
    RED: 255
    BLUE: 0
    GREEN: 255
  particleShape: spot

# MODIFIED MY i998979
barItem:
  slots: 63
  prevpage:
    ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: DIAMOND_HOE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §7下一頁
      lore:
      - §f按我翻到下一頁
      ItemFlags:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
      - HIDE_UNBREAKABLE
      - HIDE_DESTROYS
      - HIDE_PLACED_ON
      - HIDE_POTION_EFFECTS
      Unbreakable: true
      Damage: 36
  nextpage:
    ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: DIAMOND_HOE
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §7上一頁
      lore:
      - §f按我翻到上一頁
      ItemFlags:
      - HIDE_ENCHANTS
      - HIDE_ATTRIBUTES
      - HIDE_UNBREAKABLE
      - HIDE_DESTROYS
      - HIDE_PLACED_ON
      - HIDE_POTION_EFFECTS
      Unbreakable: true
      Damage: 36
  # You can only add !!LESS THAN OR EQUAL TO 9!! items here, otherwise the rest of them will flow out
  header:
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是第一行
      lore:
      - §4我是第一行哈哈哈哈
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是第一行
      lore:
      - §4我是第一行哈哈哈哈
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是第一行
      lore:
      - §4我是第一行哈哈哈哈
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是第一行
      lore:
      - §4我是第一行哈哈哈哈
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是第一行
      lore:
      - §4我是第一行哈哈哈哈
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是第一行
      lore:
      - §4我是第一行哈哈哈哈
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是第一行
      lore:
      - §4我是第一行哈哈哈哈
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是第一行
      lore:
      - §4我是第一行哈哈哈哈
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是第一行
      lore:
      - §4我是第一行哈哈哈哈
  # You can only add !!LESS THAN OR EQUAL TO 9!! items here, otherwise the rest of them will flow out
  footer:
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是最後一行
      lore:
      - §4我是最後一行呵呵呵呵
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是最後一行
      lore:
      - §4我是最後一行呵呵呵呵
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是最後一行
      lore:
      - §4我是最後一行呵呵呵呵
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是最後一行
      lore:
      - §4我是最後一行呵呵呵呵
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是最後一行
      lore:
      - §4我是最後一行呵呵呵呵
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是最後一行
      lore:
      - §4我是最後一行呵呵呵呵
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是最後一行
      lore:
      - §4我是最後一行呵呵呵呵
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是最後一行
      lore:
      - §4我是最後一行呵呵呵呵
  - ==: org.bukkit.inventory.ItemStack
    v: 1631
    type: BARRIER
    meta:
      ==: ItemMeta
      meta-type: UNSPECIFIC
      display-name: §e§l我是最後一行
      lore:
      - §4我是最後一行呵呵呵呵
